name: spotify
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.1
  firebase_storage: ^10.2.17
  provider: ^6.0.3
  youtube_explode_dart: ^1.11.0
  path_provider: ^2.0.11
  flutter_neumorphic: ^3.2.0
  assets_audio_player: 3.0.6 
  progress_indicators: ^1.0.0
  shimmer: ^2.0.0
  side_navigation: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/music_icon.png"

flutter:

  uses-material-design: true

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf

  
  
